### ISSUE TITLE
Investigate IE8 console.log/warn.bind

### ISSUE THREAD

**Issue by kenwheeler** [FormidableLabs/biff#3]
Investigate whether 

```
warn = (console.warn || console.log).bind(console)
```

introduces errors in IE8

**Comment by ryan-roemer** [comment]
Actually thinking about it more `console.ANYTHING` shouldn't even be called in IE8 straight up. I think the options for biff should be:
- Remove all `console` usage. OR
- Polyfill `console.log` down to IE8. OR
- Wrap any calls to `console.ANYTHING` in `process.env.NODE_ENV === 'development'` like React does. (With the expectation that you "build this out" eventually). However, test case like ours would still hit this issue.

**Comment by kenwheeler** [comment]
After reviewing how this is handled in React as well as React Router I've found the following:
- Logging is done via `invariant` and `warning`, both helpers for throwing errors and warnings respectively
- The method internals in React are wrapped with a conditional that checks for `__DEV__` which is the env flag
- React Router requires React as a dev dep & peer dep and requires these methods out of `react/lib`. Because the aren't in the context of the environment, it's necessary to call `("production" !== process.env.NODE_ENV ? invariant(args)`
- React's console support for IE8 when any env that isn't product is passed, requires manually including a polyfill.

Given the above, we could either:
- Add react as a dep, import their libs and use the env check wrapper when calling. This doesn't solve for dev mode in IE8 though
- Roll a custom module that takes a type parameter that allows for logs, errors and warns. The production flag would be checked internally, and console methods would be polyfilled back to IE8. It could look like `logger(condition, type, "Messaging")`

Thoughts?

cc @ryan-roemer

**Comment by ryan-roemer** [comment]
@kenwheeler -- Separate from all of this, I am planning on open sourcing a `ConsoleStream` plugin for client-side Bunyan. Maybe best bet is a I make a separate repo of a very tight console wrapper script that just takes care of everything in a sane, tested way...

**Comment by kenwheeler** [comment]
Sounds like a plan.

**Comment by ryan-roemer** [comment]
@kenwheeler -- OK, I've got a log wrapper that is tested on all the browsers we'd need to worry about: https://github.com/FormidableLabs/simple-console

I would use this as an instance, e.g. `var con = new SimpleConsole();` and **not** as a polyfill, since you don't want the library making polyfill choices just by importing it.

I'll look to slim the library down over time. I also understand if it's too big for biff right now -- if so, maybe you can just snake the very specific `console.warn` and `console.log` stuff you need and provide a smaller wrapper just for that in biff...

**Comment by kenwheeler** [comment]
@ryan-roemer This looks great, I don't think the size will be an issue in the interest of reliable logging. Does this automatically suppress logging in production? Or do I still need to wrap the calls with an env check?

**Comment by kenwheeler** [comment]
Just saw the sinkhole option. Branching now.

**Comment by ryan-roemer** [comment]
@kenwheeler -- Wow you're fast. Yeah, just tweaked things and documented https://github.com/FormidableLabs/simple-console#noop-logger with React use cases in mind.

Also, make sure to watch https://travis-ci.org/FormidableLabs/simple-console/builds/52591532 for new version `v0.0.4` -- the devil in the details with this library is actually the **testing** everywhere, and much less the actual implementation ;)

**Comment by kenwheeler** [comment]
@ryan-roemer I just replaced invariant and warn in a local branch, and I noticed in a failing test that console.error doesn't actually throw an exception. Do you think there is value here in actually throwing an exception in the event of an invariant?

**Comment by kenwheeler** [comment]
For clarification, not that console.error should throw an error, but is the replacement of a throw with a console.error a bad idea?

**Comment by ryan-roemer** [comment]
@kenwheeler -- Generally speaking, if the library means to communicate an error, throwing or passing an error object to the callback is expected. I generally wouldn't swallow errors in production (i.e., what switching to `console.error` implies) unless it's a case where the library's state is safe to continue after the error has occurred...

So, `tl;dr` it's a judgement call, but have a bias for bubbling up errors.

**Comment by kenwheeler** [comment]
Resolved via 1f4c3c8a8c0a3d45fda2aad1e8a887807a83bccd
