### ISSUE TITLE
Simple Console error when rendering to String

### ISSUE THREAD

**Issue by zolar** [FormidableLabs/biff#8]
Getting error when doing a React.renderToString.
biff/node_modules/simple-console/simple-console.js: line 104.
Might need to change 
_console = window.console || null; 
to
_console = ( window && window.console ) ? window.console : null;

**Comment by kenwheeler** [comment]
What's the actual error?

**Comment by ryan-roemer** [comment]
Ah! My use cases so far have just integrated `simple-console` as a client-only transport in server-side rendered apps.

https://github.com/FormidableLabs/simple-console/pull/6 should fix and I'll do a new release once CI passes on that PR.

**Comment by kenwheeler** [comment]
Thanks @ryan-roemer

**Comment by ryan-roemer** [comment]
@zolar @kenwheeler -- `simple-console@0.1.1` is now Node compatible.

**Comment by kenwheeler** [comment]
@zolar @ryan-roemer Thanks! Biff is now bumped to 0.1.6, with the updated simple-console
